export enum EndpointAccessControlCommand {
  isSupported = "endpoint.access_control.is_supported",
  getUserCapabilitiesCached = "endpoint.access_control.get_user_capabilities_cached",
  getCredentialCapabilitiesCached = "endpoint.access_control.get_credential_capabilities_cached",
  getUser = "endpoint.access_control.get_user",
  getUserCached = "endpoint.access_control.get_user_cached",
  getUsers = "endpoint.access_control.get_users",
  getUsersCached = "endpoint.access_control.get_users_cached",
  setUser = "endpoint.access_control.set_user",
  deleteUser = "endpoint.access_control.delete_user",
  deleteAllUsers = "endpoint.access_control.delete_all_users",
  getCredential = "endpoint.access_control.get_credential",
  getCredentialCached = "endpoint.access_control.get_credential_cached",
  getCredentials = "endpoint.access_control.get_credentials",
  getCredentialsCached = "endpoint.access_control.get_credentials_cached",
  setCredential = "endpoint.access_control.set_credential",
  deleteCredential = "endpoint.access_control.delete_credential",
  startCredentialLearn = "endpoint.access_control.start_credential_learn",
  cancelCredentialLearn = "endpoint.access_control.cancel_credential_learn",
  getAdminCode = "endpoint.access_control.get_admin_code",
  setAdminCode = "endpoint.access_control.set_admin_code",
}
