export enum EndpointCommand {
  invokeCCAPI = "endpoint.invoke_cc_api",
  getUserCapabilitiesCached = "endpoint.get_user_capabilities_cached",
  getCredentialCapabilitiesCached = "endpoint.get_credential_capabilities_cached",
  getUser = "endpoint.get_user",
  getUserCached = "endpoint.get_user_cached",
  getUsers = "endpoint.get_users",
  getUsersCached = "endpoint.get_users_cached",
  setUser = "endpoint.set_user",
  deleteUser = "endpoint.delete_user",
  deleteAllUsers = "endpoint.delete_all_users",
  getCredential = "endpoint.get_credential",
  getCredentialCached = "endpoint.get_credential_cached",
  getCredentials = "endpoint.get_credentials",
  getCredentialsCached = "endpoint.get_credentials_cached",
  setCredential = "endpoint.set_credential",
  deleteCredential = "endpoint.delete_credential",
  startCredentialLearn = "endpoint.start_credential_learn",
  cancelCredentialLearn = "endpoint.cancel_credential_learn",
  getAdminCode = "endpoint.get_admin_code",
  setAdminCode = "endpoint.set_admin_code",
  supportsCCAPI = "endpoint.supports_cc_api",
  supportsCC = "endpoint.supports_cc",
  controlsCC = "endpoint.controls_cc",
  isCCSecure = "endpoint.is_cc_secure",
  getCCVersion = "endpoint.get_cc_version",
  getNodeUnsafe = "endpoint.get_node_unsafe",
  tryGetNode = "endpoint.try_get_node",
  setRawConfigParameterValue = "endpoint.set_raw_config_parameter_value",
  getRawConfigParameterValue = "endpoint.get_raw_config_parameter_value",
  // Undocumented
  getCCs = "endpoint.get_ccs",
  // Undocumented
  maySupportBasicCC = "endpoint.may_support_basic_cc",
  // Undocumented
  wasCCRemovedViaConfig = "endpoint.was_cc_removed_via_config",
}
