export enum NodeCommand {
  setValue = "node.set_value",
  refreshInfo = "node.refresh_info",
  getDefinedValueIDs = "node.get_defined_value_ids",
  getValueMetadata = "node.get_value_metadata",
  beginFirmwareUpdate = "node.begin_firmware_update",
  abortFirmwareUpdate = "node.abort_firmware_update",
  pollValue = "node.poll_value",
  setRawConfigParameterValue = "node.set_raw_config_parameter_value",
  refreshValues = "node.refresh_values",
  refreshCCValues = "node.refresh_cc_values",
  ping = "node.ping",
  getFirmwareUpdateCapabilities = "node.get_firmware_update_capabilities",
  hasSecurityClass = "node.has_security_class",
  getHighestSecurityClass = "node.get_highest_security_class",
}
